### ISSUE TITLE
index of range error when receive malformed client command

### ISSUE THREAD

**Issue by Matrix0xCC** [Matrix0xCC/gotunnel#5]
```
2019/04/04 10:56:15 [32 245 123 3 160 46 169 163 12 159 224 42 197 135 127 139 80 169 103 179 153 137 213 170 246 150 187 177 132 27 47 222 225 105 108 60 233 3 148 94 98 117 108 52 173 133 199 230 87 76 229 121 30 5 86 139 28 41 98 85 125 6 148 21 249 165 198 15 173 143 163 89 208 92 94 30 59 149 172 233 199 134 23 230 254 2 3 132 196 111 233
208 157 85 221 151 90 95 103 153 65 47 19 133 161 193 199 163 244 27 101 62 104 147 188 125 171 224 134 185 239 15 51 73 85 149 185 165 127 232 82 249 138 35 243 44 205 124
117 87 74 8 121 115 184 65 115 154 158 17 246 21 91 117 206 221 167 153 178 45 6 84 205 4 107 239 106 153 57 8 200 5 246 160 16 238 222 26 134 139 188 137 123 180 1 182 95 190 64 80 227 233 162 55 123 176 165 230 79 132 172 171 250 23 164 51 32 187 59 49 141 183 135 230 228 127 206 172 160 164 209 120 79 144 11 197 114 215 199 6 115 42 185 24 50 144 208 181 250 84 183 190 26 6 48 205 227 9 230 26 40 143 153 245 181]
2019/04/04 10:56:15 unsupported command
2019/04/04 10:56:20 [55 234 73 101 231]
panic: runtime error: index out of range

goroutine 60929 [running]:
protocol.DecodeClientCommand(0xc42007e800, 0x5, 0x400, 0xc42000c140, 0x5, 0x0)
        /home/mycatclaw/gotunnel/src/protocol/protocol.go:66 +0x470
main.handleClientCommand(0x7fe9ad06e3a0, 0xc42023a0c0, 0xc42023a0c0, 0x7fe9ad06e3a0, 0xc42023a0c0, 0x0)
        /home/mycatclaw/gotunnel/src/proxy.go:66 +0x16e
main.handleConnInServerMode(0x6160a0, 0xc42023a0c0, 0xc42000c200)
        /home/mycatclaw/gotunnel/src/proxy.go:100 +0x5d
created by main.main
        /home/mycatclaw/gotunnel/src/proxy.go:31 +0x1a1

```

**Comment by Matrix0xCC** [comment]
1. secrecy
Symmetric pre-shared key encryption was used to protect data secrecy.

2. integrity
Not supported.

3. authentication
Not supported.

4. traffic characteristic
Firewall can be bypassed easily with the help of the private encrypted protocol.
